apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
rules:
{{- range .Values.clusterRole.rules }}
  - apiGroups:
      - ""
    resources: {{ toYaml .resources | quote }}
    verbs: {{ toYaml .verbs | quote }}
{{- end }}