apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-demo.fullname" . }}
  labels:
    {{- include "argo-demo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "argo-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argo-demo.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: persistent-storage
              mountPath: /mountPoint
          {{- end }}
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: s3-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: {{ .Values.s3.pv.capacity.storage }}
  accessModes:
    - {{ .Values.s3.pv.accessModes }}
  mountOptions:
    {{- toYaml .Values.s3.pv.mountOptions | nindent 2 }}
  csi:
    driver: {{ .Values.s3.pv.csi.driver }}
    volumeHandle: {{ .Values.s3.pv.csi.volumeHandle }}
    volumeAttributes:
      bucketName: {{ .Values.s3.pv.csi.volumeAttributes.bucketName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
  namespace: {{ .Values.deployment.namespace }}
spec:
  accessModes:
    - {{ .Values.s3.pvc.accessModes }}   # 여기 수정
  storageClassName: ""
  resources:
      requests:
        storage: {{ .Values.s3.pvc.resources.requests.storage }}
  volumeName: s3-pv

