apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.labels.app }}
    project: {{ .Values.deployment.labels.project }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
            cpu: {{ .Values.deployment.resources.limits.cpu }}
        volumeMounts:
          - name: persistent-storage
            mountPath: {{ .Values.deployment.volumeMounts.mountPath }}
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: s3-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: {{ .Values.s3.pv.capacity.storage }}
  accessModes:
    - {{ .Values.s3.pv.accessModes }}
  mountOptions:
    {{- toYaml .Values.s3.pv.mountOptions | nindent 2 }}
  csi:
    driver: {{ .Values.s3.pv.csi.driver }}
    volumeHandle: {{ .Values.s3.pv.csi.volumeHandle }}
    volumeAttributes:
      bucketName: {{ .Values.s3.pv.csi.volumeAttributes.bucketName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
spec:
  accessModes:
    - {{ .Values.s3.pvc.accessModes }}   # 여기 수정
  storageClassName: {{ .Values.s3.pvc.storageClassName }}
  resources:
      requests:
        storage: {{ .Values.s3.pvc.resources.requests.storage }}
  volumeName: s3-pv
