# argo-helm/external-dns-chart/template/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount
  labels:
    app.kubernetes.io/name: external-dns
  namespace: {{ .Values.externalDNS.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::477159410287:role/{{ .Values.externalDNS.roleName }}