# ingress-chart/values.yaml
ingress:
  name: my-ingress
  namespace: stock-city
  loadBalancerName: stock-alb
  certificateArn: arn:aws:acm:ap-northeast-2:477159410287:certificate/8f983667-7eee-4d20-9072-3d88255f37cc
  serviceName: web-svc
  hostname: su.itbank08.link

service:
  name: web-svc
  labels:
    app: web-app
    project: stock-city
  namespace: stock-city
  serviceType: NodePort
  port: 80

deployment:
  name: web-deploy
  labels:
    app: web-app
    project: stock-city
  namespace: stock-city
  replicas: 1
  strategy:
    maxUnavailable: 2
    maxSurge: 1
  containerName: web-app
  image:
    repository: 477159410287.dkr.ecr.ap-northeast-2.amazonaws.com/itbank08
    tag: 99
  containerPort: 80
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"

externalDNS:
  roleName: sua-EKSExternalDNSRole
  domainFilter: itbank08.link
  provider: aws
  policy: sync
  awsZoneType: public
  registry: txt
  txtOwnerId: Z00635613ERGDRY3ESU8T
  namespace: stock-city

clusterRoleBinding:
  subjects:
    - serviceAccount: external-dns
      namespace: stock-city

s3:
  pv:
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteMany
    mountOptions:
      - allow-delete
      - region=ap-northeast-2
    csi:
      driver: s3.csi.aws.com
      volumeHandle: s3-csi-driver-volume
      volumeAttributes:
        bucketName: stockcity-s3
  pvc:
    accessModes:
      - ReadWriteMany
    storageClassName: ""
    resources:
      requests:
        storage: 50Gi
