# ingress-chart/values.yaml
ingress:
  name: my-ingress
  namespace: stock-city
  loadBalancerName: stock-alb
  certificateArn: arn:aws:acm:ap-northeast-2:477159410287:certificate/a3b57eac-e021-4ad2-b393-88cba859d70f
  serviceName: web-svc
  hostname: su.itbank08.link

service:
  name: web-svc
  labels:
    app: web-app
    project: stock-city
  namespace: stock-city
  serviceType: NodePort
  port: 80

deployment:
  replicaCount: 1
  image:
    repository: 477159410287.dkr.ecr.ap-northeast-2.amazonaws.com/itbank08
    tag: latest
  containerPort: 80
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"

externalDNS:
  roleName: sua-EKSExternalDNSRole
  domainFilter: itbank08.link
  provider: aws
  policy: sync
  awsZoneType: public
  registry: txt
  txtOwnerId: Z00635613ERGDRY3ESU8T

clusterRole:
  rules:
    - apiGroups: [""]
      resources: ["services","endpoints","pods","nodes"]
      verbs: ["get","watch","list"]
    - apiGroups: ["extensions","networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get","watch","list"]

clusterRoleBinding:
  subjects:
    - serviceAccount: external-dns
      namespace: stock-city